---
action:
- else:
  - data:
      brightness_pct: 80
      color_temp: 500
      transition: 0
    service: light.turn_on
    target:
      entity_id: light.kitchen_downlights
  if:
  - condition: state
    entity_id: light.kitchen_downlights
    state: "on"
  then:
  - data:
      transition: 0
    service: light.turn_off
    target:
      entity_id: light.kitchen_downlights
alias: Kitchen Lights
mode: single
trigger:
- entity_id:
  - binary_sensor.kitchen_switch_1
  - binary_sensor.kitchen_switch_2
  - binary_sensor.kitchen_switch_3
  - binary_sensor.kitchen_switch_4
  from: "off"
  platform: state
  to: "on"
