---
action:
- data:
    brightness_pct: 100
    color_temp: 153
    transition: 0
  service: light.turn_on
  target:
    entity_id: light.kitchen_downlights
alias: Kitchen Lights (Bright)
mode: single
trigger:
- entity_id:
  - binary_sensor.kitchen_switch_1
  - binary_sensor.kitchen_switch_2
  - binary_sensor.kitchen_switch_3
  - binary_sensor.kitchen_switch_4
  for:
    seconds: 2
  from: "off"
  platform: state
  to: "on"
