---
action:
- else:
  - data:
      brightness_pct: 80
      color_temp: 500
      transition: 0
    service: light.turn_on
    target:
      entity_id: light.bedroom_tablelights
  if:
  - condition: state
    entity_id: light.bedroom_lights
    state: "on"
  then:
  - else:
    - data:
        brightness_pct: 80
        color_temp: 500
        transition: 0
      service: light.turn_on
      target:
        entity_id: light.bedroom_downlights
    if:
    - condition: or
      conditions:
      - condition: state
        entity_id: light.bedroom_lights
        for:
          seconds: 5
        state: "on"
      - condition: state
        entity_id: light.bedroom_downlights
        state: "on"
    then:
    - data:
        transition: 0
      service: light.turn_off
      target:
        entity_id: light.bedroom_lights
alias: Bedroom Lights
mode: single
trigger:
- entity_id:
  - binary_sensor.bedroom_switch_1
  - binary_sensor.bedroom_switch_2
  - binary_sensor.bedroom_switch_3
  from: "off"
  platform: state
  to: "on"
