---
action:
- else:
  - data:
      brightness_pct: 80
      color_temp: 500
      transition: 1
    service: light.turn_on
    target:
      entity_id: light.bedroom_tablelights
  if:
  - condition: state
    entity_id: light.bedroom_tablelights
    state: "on"
  then:
  - data:
      transition: 1
    service: light.turn_off
    target:
      entity_id: light.bedroom_tablelights
alias: Bedroom Tablelights
mode: single
trigger:
- entity_id:
  - sensor.bedroom_switch_1
  - sensor.bedroom_switch_2
  from: "OFF"
  platform: state
  to: SINGLE
