---
cards:
- entities:
  - entities:
    - entity: sensor.lounge_terrace_door_battery
      name: Sensor Battery
    head:
      entity: binary_sensor.lounge_terrace_door
      name: Lounge Door
    type: custom:fold-entity-row
  type: entities
- entities:
  - entities:
    - entity: sensor.bedroom_terrace_door_battery
      name: Sensor Battery
    head:
      entity: binary_sensor.bedroom_terrace_door
      name: Bedroom Door
    type: custom:fold-entity-row
  type: entities
columns: 1
square: false
title: Security
type: grid
