---
repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: mixed-line-ending
  - id: check-xml
  - args:
    - --unsafe
    id: check-yaml
  - id: sort-simple-yaml
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
- hooks:
  - id: docker-compose-check
  repo: https://github.com/IamTheFij/docker-pre-commit.git
  rev: v1.0.0
- hooks:
  - id: yamllint
  repo: https://github.com/adrienverge/yamllint.git
  rev: v1.27.1
- hooks:
  - id: black
  repo: https://github.com/psf/black.git
  rev: 19.3b0
