---
cards:
- entities:
  - entities:
    - entity: sensor.kitchen_humidity
      name: Humidity
    - entity: sensor.kitchen_pressure
      name: Pressure
    - entity: sensor.kitchen_climate_battery
      name: Sensor Battery
    head:
      entity: sensor.kitchen_temperature
      name: Temperature
      type: custom:multiple-entity-row
    type: custom:fold-entity-row
  type: entities
- entity: climate.kitchen_hvac
  type: thermostat
columns: 1
square: false
title: Climate
type: grid
