---
cards:
- entities:
  - entities:
    - entities:
      - entities:
        - entity: light.kitchen_downlight_01
          name: Downlight 01
          entities:
          - entity: sensor.kitchen_downlight_01_power
            name: Power
          type: custom:multiple-entity-row
        - entity: light.kitchen_downlight_02
          name: Downlight 02
          entities:
          - entity: sensor.kitchen_downlight_02_power
            name: Power
          type: custom:multiple-entity-row
        - entity: light.kitchen_downlight_05
          name: Downlight 05
          entities:
          - entity: sensor.kitchen_downlight_05_power
            name: Power
          type: custom:multiple-entity-row
        - entity: light.kitchen_downlight_06
          name: Downlight 06
          entities:
          - entity: sensor.kitchen_downlight_06_power
            name: Power
          type: custom:multiple-entity-row
        - entity: light.kitchen_downlight_09
          name: Downlight 09
          entities:
          - entity: sensor.kitchen_downlight_09_power
            name: Power
          type: custom:multiple-entity-row
        - entity: light.kitchen_downlight_10
          name: Downlight 10
          entities:
          - entity: sensor.kitchen_downlight_10_power
            name: Power
          type: custom:multiple-entity-row
        head:
          entity: light.kitchen_downlights_a
          name: Downlights A
          entities:
          - entity: sensor.kitchen_downlights_a_power
            name: Power
          type: custom:multiple-entity-row
        type: custom:fold-entity-row
      - entities:
        - entity: light.kitchen_downlight_03
          name: Downlight 03
          entities:
          - entity: sensor.kitchen_downlight_03_power
            name: Power
          type: custom:multiple-entity-row
        - entity: light.kitchen_downlight_04
          name: Downlight 04
          entities:
          - entity: sensor.kitchen_downlight_04_power
            name: Power
          type: custom:multiple-entity-row
        - entity: light.kitchen_downlight_07
          name: Downlight 07
          entities:
          - entity: sensor.kitchen_downlight_07_power
            name: Power
          type: custom:multiple-entity-row
        - entity: light.kitchen_downlight_08
          name: Downlight 08
          entities:
          - entity: sensor.kitchen_downlight_08_power
            name: Power
          type: custom:multiple-entity-row
        head:
          entity: light.kitchen_downlights_b
          name: Downlights B
          entities:
          - entity: sensor.kitchen_downlights_b_power
            name: Power
          type: custom:multiple-entity-row
        type: custom:fold-entity-row
      - entities:
        - entity: light.kitchen_downlight_11
          name: Downlight 11
          entities:
          - entity: sensor.kitchen_downlight_11_power
            name: Power
          type: custom:multiple-entity-row
        - entity: light.kitchen_downlight_12
          name: Downlight 12
          entities:
          - entity: sensor.kitchen_downlight_12_power
            name: Power
          type: custom:multiple-entity-row
        head:
          entity: light.kitchen_downlights_c
          name: Downlights C
          entities:
          - entity: sensor.kitchen_downlights_c_power
            name: Power
          type: custom:multiple-entity-row
        type: custom:fold-entity-row
      head:
        entity: light.kitchen_downlights
        name: Downlights
        entities:
        - entity: sensor.kitchen_downlights_power
          name: Power
        type: custom:multiple-entity-row
      type: custom:fold-entity-row
    head:
      entity: light.kitchen_lights
      name: Lights
      entities:
      - entity: sensor.kitchen_lights_power
        name: Power
      type: custom:multiple-entity-row
    type: custom:fold-entity-row
  type: entities
columns: 1
square: false
title: Lights
type: grid