---
cards:
- entity: media_player.kitchen_shield
  type: media-control
- entity: media_player.kitchen_speaker
  type: media-control
- entities:
  - switch.kitchen_google_mini
  type: entities
columns: 1
square: false
title: Media Players
type: grid
