---
cards:
- entities:
  - entities:
    - entity: sensor.kitchen_backyard_door_battery
      name: Sensor Battery
    head:
      entity: binary_sensor.kitchen_backyard_door
      name: Backyard Door
    type: custom:fold-entity-row
  type: entities
columns: 1
square: false
title: Security
type: grid
