---
sensor:
- unique_id: stairwell_downlights_power
  name: Stairwell Downlights Power
  device_class: power
  unit_of_measurement: W
  state: |-
    {{
      states('sensor.stairwell_downlights_a_power') | float(0.0) +
      states('sensor.stairwell_downlights_b_power') | float(0.0) +
      states('sensor.stairwell_downlights_c_power') | float(0.0)
    }}