---
device_class: power
name: Stairwell Downlight 2 Power
state: |-
  {{
    (
      (
        (states('sensor.stairwell_downlights_a_power') | float(0.0))
        /
        (state_attr('light.stairwell_downlights_a', 'entity_id') | list | length)
      )
      if (state_attr('light.stairwell_downlights_a', 'entity_id') | select('is_state', 'on') | list | length) == 0 else
      0
    )
    if states('light.stairwell_downlight_2') == 'off' else
    (
      (states('sensor.stairwell_downlights_a_power') | float(0.0))
      /
      (state_attr('light.stairwell_downlights_a', 'entity_id') | select('is_state', 'on') | list | length)
    )
  }}
unique_id: stairwell_downlight_2_power
unit_of_measurement: W
