---
device_class: power
name: Stairwell Lights Power
state: |-
  {{
    states('sensor.stairwell_downlights_power') | float(0.0) +
    states('sensor.stairwell_nightlights_power') | float(0.0)
  }}
unique_id: stairwell_lights_power
unit_of_measurement: W
