---
device_class: power
name: Stairwell Nightlight 3 Power
state: |-
  {{ (states('sensor.stairwell_nightlights_power') | float(0.0)) / 6 }}
unique_id: stairwell_nightlight_3_power
unit_of_measurement: W
