---
sensor:
- unique_id: stairwell_nightlight_6_power
  name: Stairwell Nightlight 6 Power
  device_class: power
  unit_of_measurement: W
  state: |-
    {{ (states('sensor.stairwell_nightlights_power') | float(0.0)) / 6 }}