---
device_class: power
name: Stairwell Nightlight 1 Power
state: |-
  {{ (states('sensor.stairwell_nightlights_power') | float(0.0)) / 6 }}
unique_id: stairwell_nightlight_1_power
unit_of_measurement: W
