---
action:
- else:
  - service: switch.turn_off
    target:
      entity_id: switch.lounge_ld
  if:
  - condition: template
    value_template: "{{ is_state_attr('media_player.amplifier','source','LD') }}"
  then:
  - service: switch.turn_on
    target:
      entity_id: switch.lounge_ld
alias: Lounge LD power
mode: single
trigger:
- attribute: source
  entity_id:
  - media_player.amplifier
  for:
    seconds: 5
  platform: state
  to: LD
- attribute: source
  entity_id:
  - media_player.amplifier
  for:
    seconds: 10
  from: LD
  platform: state
