---
action:
- data:
    brightness_pct: 100
    color_temp: 153
    transition: 0
  service: light.turn_on
  target:
    entity_id: light.lounge_lights
alias: Lounge Lights (Bright)
mode: single
trigger:
- entity_id:
  - binary_sensor.lounge_switch_1
  - binary_sensor.lounge_switch_2
  for:
    seconds: 2
  from: "off"
  platform: state
  to: "on"
