---
action:
- service: switch.turn_off
  target:
    entity_id: switch.laundry_fan
alias: Laundry Fan Off
mode: single
trigger:
- entity_id:
  - light.laundry_downlights
  for:
    seconds: 30
  platform: state
  to: "off"
