---
device_class: power
name: Ensuite Lights Power
state: |-
  {{
    states('sensor.ensuite_downlights_power') | float(0.0) +
    states('sensor.ensuite_nightlights_power') | float(0.0)
  }}
unique_id: ensuite_lights_power
unit_of_measurement: W
