---
cards:
- entities:
  - entities:
    - entities:
      - entities:
        - entity: sensor.driveway_downlight_1_power
          name: Power
        entity: light.driveway_downlight_1
        name: Downlight 1
        toggle: true
        type: custom:multiple-entity-row
      - entities:
        - entity: sensor.driveway_downlight_2_power
          name: Power
        entity: light.driveway_downlight_2
        name: Downlight 2
        toggle: true
        type: custom:multiple-entity-row
      head:
        entities:
        - entity: sensor.driveway_downlights_power
          name: Power
        entity: light.driveway_downlights
        name: Downlights
        toggle: true
        type: custom:multiple-entity-row
      type: custom:fold-entity-row
    head:
      entities:
      - entity: sensor.driveway_lights_power
        name: Power
      entity: light.driveway_lights
      name: Lights
      toggle: true
      type: custom:multiple-entity-row
    type: custom:fold-entity-row
  type: entities
columns: 1
square: false
title: Lights
type: grid
