---
action:
- else:
  - data:
      brightness_pct: 80
      color_temp: 500
      transition: 1
    service: light.turn_on
    target:
      entity_id: light.office_downlights
  if:
  - condition: state
    entity_id: light.office_lights
    state: "on"
  then:
  - data:
      transition: 1
    service: light.turn_off
    target:
      entity_id: light.office_lights
alias: Office Downlights
mode: single
trigger:
- entity_id:
  - binary_sensor.office_switch_1
  - binary_sensor.office_switch_2
  from: "ON"
  platform: state
  to: "OFF"
