---
cards:
- entities:
  - entities:
    - entity: sensor.office_entrance_driveway_battery
      name: Sensor Battery
    head:
      entity: binary_sensor.office_entrance_driveway
      name: Driveway Door
    type: custom:fold-entity-row
  type: entities
columns: 1
square: false
title: Security
type: grid
