---
cards:
- entities:
  - entities:
    - entity: sensor.ensuite_humidity
      name: Humidity
    - entity: sensor.ensuite_pressure
      name: Pressure
    - entity: sensor.ensuite_climate_battery
      name: Sensor Battery
    head:
      entity: sensor.ensuite_temperature
      name: Temperature
      type: custom:multiple-entity-row
    type: custom:fold-entity-row
  type: entities
- entities:
  - entities:
    - entity: sensor.ensuite_fan_power
      name: false
    entity: switch.ensuite_fan
    name: Fan
    toggle: true
    type: custom:multiple-entity-row
  type: entities
columns: 1
square: false
title: Climate
type: grid
