---
cards:
- entities:
  - entities:
    - entities:
      - entity: light.ensuite_downlight_1
        name: Downlight 1
        entities:
        - entity: sensor.ensuite_downlight_1_power
          name: Power
        toggle: true
        type: custom:multiple-entity-row
      head:
        entity: light.ensuite_downlights
        name: Downlights
        entities:
        - entity: sensor.ensuite_downlights_power
          name: Power
        toggle: true
        type: custom:multiple-entity-row
      type: custom:fold-entity-row
    head:
      entity: light.ensuite_lights
      name: Lights
      entities:
      - entity: sensor.ensuite_lights_power
        name: Power
      toggle: true
      type: custom:multiple-entity-row
    type: custom:fold-entity-row
  type: entities
columns: 1
square: false
title: Lights
type: grid