---
cards:
- entities:
  - entities:
    - entities:
      - entities:
        - entity: sensor.ensuite_downlight_1_power
          name: false
        entity: light.ensuite_downlight_1
        name: Downlight 1
        toggle: true
        type: custom:multiple-entity-row
      head:
        entities:
        - entity: sensor.ensuite_downlights_power
          name: false
        entity: light.ensuite_downlights
        name: Downlights
        toggle: true
        type: custom:multiple-entity-row
      type: custom:fold-entity-row
    - entities:
      - entities:
        - entity: sensor.ensuite_nightlight_1_power
          name: false
        entity: light.ensuite_nightlight_1
        name: Nightlight 1
        toggle: true
        type: custom:multiple-entity-row
      head:
        entities:
        - entity: sensor.ensuite_nightlights_power
          name: false
        entity: light.ensuite_nightlights
        name: Nightlights
        toggle: true
        type: custom:multiple-entity-row
      type: custom:fold-entity-row
    head:
      entities:
      - entity: sensor.ensuite_lights_power
        name: false
      entity: light.ensuite_lights
      name: Lights
      toggle: true
      type: custom:multiple-entity-row
    type: custom:fold-entity-row
  type: entities
columns: 1
square: false
title: Lights
type: grid
