---
cards:
- entities:
  - entities:
    - entity: sensor.ensuite_bedroom_door_battery
      name: Sensor Battery
    head:
      entity: binary_sensor.ensuite_bedroom_door
      name: Bedroom Door
    type: custom:fold-entity-row
  type: entities
columns: 1
square: false
title: Security
type: grid
