---
cards:
- entities:
  - entities:
    - entity: sensor.laundry_humidity
      name: Humidity
    - entity: sensor.laundry_pressure
      name: Pressure
    - entity: sensor.laundry_climate_battery
      name: Sensor Battery
    head:
      entity: sensor.laundry_temperature
      name: Temperature
      type: custom:multiple-entity-row
    type: custom:fold-entity-row
  type: entities
columns: 1
square: false
title: Climate
type: grid
