---
cards:
- entities:
  - entities:
    - entities:
      - entities:
        - entity: sensor.laundry_downlight_1_power
          name: false
        entity: light.laundry_downlight_1
        name: Downlight 1
        toggle: true
        type: custom:multiple-entity-row
      - entities:
        - entity: sensor.laundry_downlight_2_power
          name: false
        entity: light.laundry_downlight_2
        name: Downlight 2
        toggle: true
        type: custom:multiple-entity-row
      head:
        entities:
        - entity: sensor.laundry_downlights_power
          name: false
        entity: light.laundry_downlights
        name: Downlights
        toggle: true
        type: custom:multiple-entity-row
      type: custom:fold-entity-row
    - entities:
      - entities:
        - entity: sensor.laundry_nightlight_1_power
          name: false
        entity: light.laundry_nightlight_1
        name: Nightlight 1
        toggle: true
        type: custom:multiple-entity-row
      head:
        entities:
        - entity: sensor.laundry_nightlights_power
          name: false
        entity: light.laundry_nightlights
        name: Nightlights
        toggle: true
        type: custom:multiple-entity-row
      type: custom:fold-entity-row
    head:
      entities:
      - entity: sensor.laundry_lights_power
        name: false
      entity: light.laundry_lights
      name: Lights
      toggle: true
      type: custom:multiple-entity-row
    type: custom:fold-entity-row
  type: entities
columns: 1
square: false
title: Lights
type: grid
