---
cards:
- entities:
  - entities:
    - entities:
      - entity: light.laundry_downlight_1
        name: Downlight 1
        secondary_info: "{{ states('sensor.laundry_downlight_1_power') | float(default=0) | round(1) }} W"
        type: custom:secondaryinfo-entity-row
      - entity: light.laundry_downlight_2
        name: Downlight 2
        secondary_info: "{{ states('sensor.laundry_downlight_2_power') | float(default=0) | round(1) }} W"
        type: custom:secondaryinfo-entity-row
      head:
        entity: light.laundry_downlights
        name: Downlights
        secondary_info: "{{ states('sensor.laundry_downlights_power') | float(default=0) | round(1) }} W"
        type: custom:secondaryinfo-entity-row
      type: custom:fold-entity-row
    head:
      entity: light.laundry_lights
      name: Lights
      secondary_info: "{{ states('sensor.laundry_lights_power') | float(default=0) | round(1) }} W"
      type: custom:secondaryinfo-entity-row
    type: custom:fold-entity-row
  type: entities
columns: 1
square: false
title: Lights
type: grid