---
action:
- else:
  - data:
      transition: 0
    service: light.turn_off
    target:
      entity_id: light.garage_lights
  if:
  - condition: state
    entity_id: binary_sensor.garage_entrance_door
    state: "on"
  then:
  - data:
      transition: 0
    service: light.turn_on
    target:
      entity_id: light.garage_lights
alias: Garage Lights
mode: single
trigger:
- event: start
  platform: homeassistant
- entity_id:
  - binary_sensor.garage_entrance_door
  platform: state
