---
sensor:
- unique_id: stairwell_nightlight_3_power
  name: Stairwell Nightlight 3 Power
  device_class: power
  unit_of_measurement: W
  state: |-
    {{ (states('sensor.stairwell_nightlights_power') | float(0.0)) / 6 }}