---
title: Moonya
views:
- cards: !include_dir_list cards/backyard
  path: backyard
  title: Backyard
- cards: !include_dir_list cards/bathroom
  path: bathroom
  title: Bathroom
- cards: !include_dir_list cards/bedroom
  path: bedroom
  title: Bedroom
- cards: !include_dir_list cards/driveway
  path: driveway
  title: Driveway
- cards: !include_dir_list cards/ensuite
  path: ensuite
  title: Ensuite
- cards: !include_dir_list cards/entrance
  path: entrance
  title: Entrance
- cards: !include_dir_list cards/garage
  path: garage
  title: Garage
- cards: !include_dir_list cards/kitchen
  path: kitchen
  title: Kitchen
- cards: !include_dir_list cards/lounge
  path: lounge
  title: Lounge
- cards: !include_dir_list cards/office
  path: office
  title: Office
- cards: !include_dir_list cards/stairwell
  path: stairwell
  title: Stairwell
