---
title: Moonya
views:
- cards: !include_dir_list cards/bathroom
  path: bathroom
  title: Bathroom
- cards: !include_dir_list cards/bedroom
  path: bedroom
  title: Bedroom
- cards: !include_dir_list cards/office
  path: office
  title: Office
- cards: !include_dir_list cards/stairwell
  path: stairwell
  title: Stairwell
