---
cards:
- entities:
  - entities:
    - entities:
      - entities:
        - entity: light.stairwell_downlight_1
          name: Downlight 1
          entities:
          - entity: sensor.stairwell_downlight_1_power
            name: Power
          type: custom:multiple-entity-row
        - entity: light.stairwell_downlight_2
          name: Downlight 2
          entities:
          - entity: sensor.stairwell_downlight_2_power
            name: Power
          type: custom:multiple-entity-row
        head:
          entity: light.stairwell_downlights_a
          name: Downlights A
          entities:
          - entity: sensor.stairwell_downlights_a_power
            name: Power
          type: custom:multiple-entity-row
        type: custom:fold-entity-row
      - entities:
        - entity: light.stairwell_downlight_3
          name: Downlight 3
          entities:
          - entity: sensor.stairwell_downlight_3_power
            name: Power
          type: custom:multiple-entity-row
        head:
          entity: light.stairwell_downlights_b
          name: Downlights B
          entities:
          - entity: sensor.stairwell_downlights_b_power
            name: Power
          type: custom:multiple-entity-row
        type: custom:fold-entity-row
      - entities:
        - entity: light.stairwell_downlight_4
          name: Downlight 4
          entities:
          - entity: sensor.stairwell_downlight_4_power
            name: Power
          type: custom:multiple-entity-row
        head:
          entity: light.stairwell_downlights_c
          name: Downlights C
          entities:
          - entity: sensor.stairwell_downlights_c_power
            name: Power
          type: custom:multiple-entity-row
        type: custom:fold-entity-row
      head:
        entity: light.stairwell_downlights
        name: Downlights
        entities:
        - entity: sensor.stairwell_downlights_power
          name: Power
        type: custom:multiple-entity-row
      type: custom:fold-entity-row
    head:
      entity: light.stairwell_lights
      name: Lights
      entities:
      - entity: sensor.stairwell_lights_power
        name: Power
      type: custom:multiple-entity-row
    type: custom:fold-entity-row
  type: entities
columns: 1
square: false
title: Lights
type: grid