---
cards:
- entities:
  - entities:
    - entities:
      - entities:
        - entity: light.stairwell_downlight_1
          name: Downlight 1
          secondary_info: "{{states('sensor.stairwell_downlight_1_power') | round(1) }} W"
          type: custom:secondaryinfo-entity-row
        - entity: light.stairwell_downlight_2
          name: Downlight 2
          secondary_info: "{{states('sensor.stairwell_downlight_2_power') | round(1) }} W"
          type: custom:secondaryinfo-entity-row
        head:
          entity: light.stairwell_downlights_a
          name: Downlights A
          secondary_info: "{{states('sensor.stairwell_downlights_a_power') | round(1) }} W"
          type: custom:secondaryinfo-entity-row
        type: custom:fold-entity-row
      - entities:
        - entity: light.stairwell_downlight_3
          name: Downlight 3
          secondary_info: "{{states('sensor.stairwell_downlight_3_power') | round(1) }} W"
          type: custom:secondaryinfo-entity-row
        head:
          entity: light.stairwell_downlights_b
          name: Downlights B
          secondary_info: "{{states('sensor.stairwell_downlights_b_power') | round(1) }} W"
          type: custom:secondaryinfo-entity-row
        type: custom:fold-entity-row
      - entities:
        - entity: light.stairwell_downlight_4
          name: Downlight 4
          secondary_info: "{{states('sensor.stairwell_downlight_4_power') | round(1) }} W"
          type: custom:secondaryinfo-entity-row
        head:
          entity: light.stairwell_downlights_c
          name: Downlights C
          secondary_info: "{{states('sensor.stairwell_downlights_c_power') | round(1) }} W"
          type: custom:secondaryinfo-entity-row
        type: custom:fold-entity-row
      head:
        entity: light.stairwell_downlights
        name: Downlights
        secondary_info: "{{states('sensor.stairwell_downlights_power') | round(1) }} W"
        type: custom:secondaryinfo-entity-row
      type: custom:fold-entity-row
    head:
      entity: light.stairwell_lights
      name: Lights
      secondary_info: "{{states('sensor.stairwell_lights_power') | round(1) }} W"
      type: custom:secondaryinfo-entity-row
    type: custom:fold-entity-row
  type: entities
columns: 1
square: false
title: Lights
type: grid