---
cards:
- entities:
  - entities:
    - entity: sensor.office_stairwell_door_battery
      name: Sensor Battery
    head:
      entity: binary_sensor.office_stairwell_door
      name: Office Door
    type: custom:fold-entity-row
  type: entities
columns: 1
square: false
title: Security
type: grid
