---
cards:
- entities:
  - entities:
    - entities:
      - entity: light.office_downlight_1
        name: Downlight 1
        secondary_info: "{{states('sensor.office_downlight_1_power') | round(1) }} W"
        type: custom:secondaryinfo-entity-row
      - entity: light.office_downlight_2
        name: Downlight 2
        secondary_info: "{{states('sensor.office_downlight_2_power') | round(1) }} W"
        type: custom:secondaryinfo-entity-row
      - entity: light.office_downlight_3
        name: Downlight 3
        secondary_info: "{{states('sensor.office_downlight_3_power') | round(1) }} W"
        type: custom:secondaryinfo-entity-row
      - entity: light.office_downlight_4
        name: Downlight 4
        secondary_info: "{{states('sensor.office_downlight_4_power') | round(1) }} W"
        type: custom:secondaryinfo-entity-row
      head:
        entity: light.office_downlights
        name: Downlights
        secondary_info: "{{states('sensor.office_downlights_power') | round(1) }} W"
        type: custom:secondaryinfo-entity-row
      type: custom:fold-entity-row
    - entities:
      - entity: light.office_tablelight_1
        name: Tablelight 1
        secondary_info: "{{states('sensor.office_tablelight_1_power') | round(1) }} W"
        type: custom:secondaryinfo-entity-row
      - entity: light.office_tablelight_2
        name: Tablelight 2
        secondary_info: "{{states('sensor.office_tablelight_2_power') | round(1) }} W"
        type: custom:secondaryinfo-entity-row
      head:
        entity: light.office_tablelights
        name: Tablelights
        secondary_info: "{{states('sensor.office_tablelights_power') | round(1) }} W"
        type: custom:secondaryinfo-entity-row
      type: custom:fold-entity-row
    head:
      entity: light.office_lights
      name: Lights
      secondary_info: "{{states('sensor.office_lights_power') | round(1) }} W"
      type: custom:secondaryinfo-entity-row
    type: custom:fold-entity-row
  type: entities
columns: 1
square: false
title: Lights
type: grid