---
action:
- else:
  - data:
      transition: 0
    service: light.turn_off
    target:
      entity_id: light.stairwell_nightlights
  if:
  - condition: state
    entity_id: light.stairwell_downlights
    state: "on"
  then:
  - data:
      brightness_pct: 80
      color_temp: 500
      transition: 0
    service: light.turn_on
    target:
      entity_id: light.stairwell_nightlights
alias: Stairwell Nightlights
mode: single
trigger:
- entity_id:
  - light.stairwell_downlights
  platform: state
