---
cards:
- entities:
  - entities:
    - entities:
      - entities:
        - entity: sensor.lounge_downlight_1_power
          name: false
        entity: light.lounge_downlight_1
        name: Downlight 1
        toggle: true
        type: custom:multiple-entity-row
      - entities:
        - entity: sensor.lounge_downlight_2_power
          name: false
        entity: light.lounge_downlight_2
        name: Downlight 2
        toggle: true
        type: custom:multiple-entity-row
      - entities:
        - entity: sensor.lounge_downlight_3_power
          name: false
        entity: light.lounge_downlight_3
        name: Downlight 3
        toggle: true
        type: custom:multiple-entity-row
      - entities:
        - entity: sensor.lounge_downlight_4_power
          name: false
        entity: light.lounge_downlight_4
        name: Downlight 4
        toggle: true
        type: custom:multiple-entity-row
      - entities:
        - entity: sensor.lounge_downlight_5_power
          name: false
        entity: light.lounge_downlight_5
        name: Downlight 5
        toggle: true
        type: custom:multiple-entity-row
      head:
        entities:
        - entity: sensor.lounge_downlights_power
          name: false
        entity: light.lounge_downlights
        name: Downlights
        toggle: true
        type: custom:multiple-entity-row
      type: custom:fold-entity-row
    - entities:
      - entities:
        - entity: sensor.lounge_tablelight_1_power
          name: false
        entity: light.lounge_tablelight_1
        name: Tablelight 1
        toggle: true
        type: custom:multiple-entity-row
      - entities:
        - entity: sensor.lounge_tablelight_2_power
          name: false
        entity: light.lounge_tablelight_2
        name: Tablelight 2
        toggle: true
        type: custom:multiple-entity-row
      - entities:
        - entity: sensor.lounge_tablelight_3_power
          name: false
        entity: light.lounge_tablelight_3
        name: Tablelight 3
        toggle: true
        type: custom:multiple-entity-row
      - entities:
        - entity: sensor.lounge_tablelight_4_power
          name: false
        entity: light.lounge_tablelight_4
        name: Tablelight 4
        toggle: true
        type: custom:multiple-entity-row
      head:
        entities:
        - entity: sensor.lounge_tablelights_power
          name: false
        entity: light.lounge_tablelights
        name: Tablelights
        toggle: true
        type: custom:multiple-entity-row
      type: custom:fold-entity-row
    head:
      entities:
      - entity: sensor.lounge_lights_power
        name: false
      entity: light.lounge_lights
      name: Lights
      toggle: true
      type: custom:multiple-entity-row
    type: custom:fold-entity-row
  type: entities
columns: 1
square: false
title: Lights
type: grid
