---
cards:
- entities:
  - entities:
    - entities:
      - entity: light.lounge_downlight_1
        name: Downlight 1
        secondary_info: "{{states('sensor.lounge_downlight_1_power') | round(1) }} W"
        type: custom:secondaryinfo-entity-row
      - entity: light.lounge_downlight_2
        name: Downlight 2
        secondary_info: "{{states('sensor.lounge_downlight_2_power') | round(1) }} W"
        type: custom:secondaryinfo-entity-row
      head:
        entity: light.lounge_downlights
        name: Downlights
        secondary_info: "{{states('sensor.lounge_downlights_power') | round(1) }} W"
        type: custom:secondaryinfo-entity-row
      type: custom:fold-entity-row
    head:
      entity: light.lounge_lights
      name: Lights
      secondary_info: "{{states('sensor.lounge_lights_power') | round(1) }} W"
      type: custom:secondaryinfo-entity-row
    type: custom:fold-entity-row
  type: entities
columns: 1
square: false
title: Lights
type: grid