---
action:
- else:
  - data:
      transition: 0
    service: light.turn_off
    target:
      entity_id: light.bathroom_nightlights
  if:
  - condition: state
    entity_id: switch.bathroom_fan
    state: "on"
  then:
  - data:
      brightness_pct: 80
      color_temp: 500
      transition: 0
    service: light.turn_on
    target:
      entity_id: light.bathroom_nightlights
alias: Bathroom Nightlights
mode: single
trigger:
- entity_id:
  - switch.bathroom_fan
  platform: state
