---
cards:
- entities:
  - entities:
    - entities:
      - entities:
        - entity: sensor.bathroom_downlight_1_power
          name: false
        entity: light.bathroom_downlight_1
        name: Downlight 1
        toggle: true
        type: custom:multiple-entity-row
      head:
        entities:
        - entity: sensor.bathroom_downlights_power
          name: false
        entity: light.bathroom_downlights
        name: Downlights
        toggle: true
        type: custom:multiple-entity-row
      type: custom:fold-entity-row
    - entities:
      - entities:
        - entity: sensor.bathroom_nightlight_1_power
          name: false
        entity: light.bathroom_nightlight_1
        name: Nightlight 1
        toggle: true
        type: custom:multiple-entity-row
      head:
        entities:
        - entity: sensor.bathroom_nightlights_power
          name: false
        entity: light.bathroom_nightlights
        name: Nightlights
        toggle: true
        type: custom:multiple-entity-row
      type: custom:fold-entity-row
    head:
      entities:
      - entity: sensor.bathroom_lights_power
        name: false
      entity: light.bathroom_lights
      name: Lights
      toggle: true
      type: custom:multiple-entity-row
    type: custom:fold-entity-row
  type: entities
columns: 1
square: false
title: Lights
type: grid
