---
cards:
- entities:
  - entities:
    - entities:
      - entities:
        - entity: sensor.backyard_downlight_1_power
          name: Power
        entity: light.backyard_downlight_1
        name: Downlight 1
        type: custom:multiple-entity-row
      - entities:
        - entity: sensor.backyard_downlight_2_power
          name: Power
        entity: light.backyard_downlight_2
        name: Downlight 2
        type: custom:multiple-entity-row
      head:
        entities:
        - entity: sensor.backyard_downlights_power
          name: Power
        entity: light.backyard_downlights
        name: Downlights
        type: custom:multiple-entity-row
      type: custom:fold-entity-row
    head:
      entities:
      - entity: sensor.backyard_lights_power
        name: Power
      entity: light.backyard_lights
      name: Lights
      type: custom:multiple-entity-row
    type: custom:fold-entity-row
  type: entities
columns: 1
square: false
title: Lights
type: grid